global:
  scrape_interval:     30s
  evaluation_interval: 1m

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - "$ALERTMANAGER_MASTER_IP:9093"
      - "$ALERTMANAGER_SLAVE_IP:9093"

rule_files:
  - "rules/basic.yml"
  - "rules/kubernetes.yml"
  - "rules/relay.rule.yml"
  - "rules/elasticsearch.yml"

scrape_configs:
  - job_name: 'Prometheus'
    static_configs:
      - targets: ['$PROME_MASTER_IP:9091','$PROME_SLAVE_IP:9091']

  # ------------------ online-----------------------------
  # https://github.com/google/cadvisor
  - job_name: 'online-kubernetes-cadvisor'
    kubernetes_sd_configs:
      - api_server: "http://$MASTER_IP:8080"
        role: node
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):10250'
        replacement: '${1}:4194'
        target_label: __address__

  # https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml#L37
  - job_name: 'online-kubernetes-nodes'
    kubernetes_sd_configs:
      - api_server: "http://$MASTER_IP:8080"
        role: node
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):10250'
        replacement: '${1}:10255'
        target_label: __address__

  # node-export:
  - job_name: 'online-kubernetes-nodes-export'
    kubernetes_sd_configs:
      - api_server: "http://$MASTER_IP:8080"
        role: node
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):10250'
        replacement: '${1}:9100'
        target_label: __address__

  # https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml#L119
  - job_name: 'online-kubernetes-services'
    metrics_path: /probe
    params:
      module: [http_2xx]
    kubernetes_sd_configs:
      - api_server: "http://$MASTER_IP:8080"
        role: service
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probe]
        action: keep
        regex: true
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox
      - source_labels: [__param_target]
        target_label: instance
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_service_name]
        target_label: kubernetes_name

    # https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml#L156
  - job_name: 'online-kubernetes-pods'
    kubernetes_sd_configs:
      - api_server: "http://$MASTER_IP:8080"
        role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: (.+):(?:\d+);(\d+)
        replacement: ${1}:${2}
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
      - source_labels: [__meta_kubernetes_pod_container_port_number]
        action: keep
        regex: 9\d{3}

  - job_name: 'online-kubernetes-apiservers'
    kubernetes_sd_configs:
    - api_server: "http://$MASTER_IP:8080"
      role: endpoints
    scheme: http
    relabel_configs:
    - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      action: keep
      regex: default;kubernetes;https
    - source_labels: [__address__]
      regex: '(.*):6443'
      replacement: '${1}:8080'
      target_label: __address__

  - job_name: 'online-kube-state-metrics'
	# 使用nodeport暴露了state-metrics
    static_configs:
      - targets: ['$K8S_NODE_IP:30088', '$K8S_NODE_IP:30089'] 
#----------------online k8s end----------------------

# consul service discover
  - job_name: 'online-consul-node'
    consul_sd_configs:
    - server: $PROME_MASTER_IP:8560
      datacenter: online
      tag_separator: ','
      scheme: http
    relabel_configs:
    - source_labels: ['__meta_consul_address']
      target_label:  '__address__'
      replacement: '${1}:9100'
      action: 'replace'
    - source_labels: [__meta_consul_service]
      target_label:  service

# blockbox:
  - job_name: 'consul-port-check'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    consul_sd_configs:
    - server: $PROME_MASTER_IP:8560
      datacenter: online
      tag_separator: ','
      scheme: http
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115
      - source_labels: [__meta_consul_service]
        target_label:  service

# file service discover
  - job_name: 'online_basic'
    metrics_path: /metrics
    file_sd_configs:
    - files:
      - 'targets/online_basic.json'

  - job_name: 'online_app_port'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    file_sd_configs:
      - files:
        - 'targets/online_app_port.json'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115

  - job_name: 'op_es_9108'
    metrics_path: /metrics
#    params:
#      module: [tcp_connect]
    file_sd_configs:
      - files:
        - 'targets/op_es_9108.json'
  - job_name: 'op_es_9200'
    basic_auth:
      username: "elastic"
      password: "$ES_PASSWD"
    metrics_path: /_prometheus/metrics
    file_sd_configs:
      - files:
        - 'targets/op_es_9200.json'
  - job_name: 'op_cephfs_9128'
    metrics_path: /metrics
#    params:
#      module: [tcp_connect]
    file_sd_configs:
      - files:
        - 'targets/ceph_phy.json'
