groups:
- name: basic
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 10m
    labels:
      severity: 0
    annotations:
      summary: "Instance {{ $labels.instance }} down"

  - alert: port_success
    expr: probe_success < 1
    for: 1m
    labels:
      severity: 0
    annotations:
      summary: "Job: {{ $labels.job }}, Instance:{{ $labels.instance }}, service port down."

  - alert: basic_cpu_idle
    expr: avg(irate(node_cpu{mode="idle"}[5m]) * 100) by (job, instance) < 10
    for: 10m
    labels:
      severity: 2
      no_deal: 1
    annotations:
      summary: "Job: {{ $labels.job }}, Instance:{{ $labels.instance }}, cpu剩余不足10%, current_value: {{ $value }}"

  - alert: basic_cpu_insufficiency
    expr: avg(irate(node_cpu{mode="idle"}[5m]) * 100) BY (instance, job) < 20 and avg(irate(node_cpu{mode="steal"}[5m]) * 100) BY (instance, job) > 10
    for: 2m
    labels:
      severity: 2
    annotations:
      summary: "Job: {{ $labels.job }}, Instance:{{ $labels.instance }} cpu抢占>10%,cpu剩余不足30%"

  - alert: basic_cpu_insufficiency
    expr: avg(irate(node_cpu{mode="idle"}[5m]) * 100) BY (instance, job) < 20 and avg(irate(node_cpu{mode="steal"}[5m]) * 100) BY (instance, job) > 10
    for: 2m
    labels:
      severity: 2
    annotations:
      summary: "Job: {{ $labels.job }}, Instance:{{ $labels.instance }}, cpu抢占>10%,cpu剩余不足30%, current_value: {{ $value }}"

  - alert: basic_iowait
    expr: avg(irate(node_cpu{mode="iowait"}[5m]) * 100) BY (instance, job) > 20
    for: 10m
    labels:
      severity: 2
      no_deal: 1
    annotations:
      summary: "Job: {{ $labels.job }}, Instance:{{ $labels.instance }}, iowait率偏高, current_value: {{ $value }}"

  - alert: basic_mem_free
    expr: (node_memory_MemFree{service=""} + node_memory_Cached{service=""})
      / node_memory_MemTotal{service=""} * 100 < 5
    for: 60m
    labels:
      severity: 2
      no_deal: 1
    annotations:
      summary: "空闲内存占比 < 5%  current_value: {{ $value }}%"

  - alert: basic_sys_disk_usage
    expr: node_filesystem_free{mountpoint="/"} / node_filesystem_size{mountpoint="/"}
      * 100 < 20
    for: 1m
    labels:
#      severity: 1
      severity: 0
    annotations:
      summary: "Job: {{ $labels.job }}, Instance:{{ $labels.instance }}, 系统盘剩余不足20%  current_value: {{ $value }}%"

  - alert: basic_data_disk_usage
    expr: node_filesystem_free{mountpoint=~"/data|/mnt"} / node_filesystem_size{mountpoint=~"/data|/mnt"}
      * 100 < 20
    for: 1m
    labels:
      severity: 0
    annotations:
      summary: "Job: {{ $labels.job }}, Instance:{{ $labels.instance }}, 数据盘剩余不足20%  current_value: {{ $value }}%"

  - alert: node_health
    expr: up < 1
    for: 10m
    labels:
      severity: 0
    annotations:
      summary: 'ENV: {{ $labels.env }}  service: {{ $labels.service }}  IP: {{ $labels.instance }}  info: 监控实例未存活告警  current_value: {{ $value }}'

  - alert: basic_port_success
    expr: probe_success < 1
    for: 1m
    annotations:
      summary: 'ENV: {{ $labels.env }}  service: {{ $labels.service }}  IP: {{ $labels.instance }}  info: 端口未存活告警  current_value: {{ $value }}'

  - alert: sum_monitor_target
    expr: count(count(node_cpu) by (instance)) < 100
    for: 1m
    labels:
      severity: 0
    annotations:
      summary: "实例存活数<100"

  - alert: critical_http_status
    expr: probe_http_status_code != 200
    for: 3m
    labels:
      severity: 1
    annotations:
      summary: 'ENV: {{ $labels.env }}  service: {{ $labels.service }}  IP: {{ $labels.instance }}  info: 客户地址不可用  current_value: {{ $value }}'

  - alert: system_load5
    expr: node_load5 / count(count(node_cpu) without (mode)) without (cpu) > 3
    for: 3m
    labels:
      no_deal: 1
      severity: 0
    annotations:
      summary: "Job: {{ $labels.job }}, Instance:{{ $labels.instance }}, system load 过高  current_value: {{ $value }}"

