groups:
- name: kubernetes
  rules:
  # node status:
  - alert: k8s-node-DiskPressure
    expr: sum(kube_node_status_condition{condition="DiskPressure", status="true"}) BY (job, pod) > 3
    for: 30m
    labels:
      severity: 1
    annotations:
      summary: '{{ $labels.pod }}, node DiskPressure, current_value: {{ $value }}'

  - alert: k8s-node-MemoryPressure
    expr: sum(kube_node_status_condition{condition="MemoryPressure", status="true"}) BY (job, pod) > 3
    for: 30m
    labels:
      severity: 2
    annotations:
      summary: '{{ $labels.pod }}, node MemoryPressure, current_value: {{ $value }}'

  - alert: k8s-node-OutOfDisk
    expr: sum(kube_node_status_condition{condition="OutOfDisk", status="true"}) BY (job, pod) > 3
    for: 30m
    labels:
      severity: 1
    annotations:
      summary: '{{ $labels.pod }}, node OutOfDisk, current_value: {{ $value }}'

  - alert: k8s-node-PIDPressure
    expr: sum(kube_node_status_condition{condition="PIDPressure", status="true"}) BY (job, pod) > 10
    for: 30m
    labels:
      severity: 2
    annotations:


  # Pod CPU Usage
  - alert: k8s-pod-cpu-usage
    expr: sum (rate (container_cpu_usage_seconds_total{image!=""}[1m])) by (pod_name) / sum(label_join(kube_pod_container_resource_requests_cpu_cores, "pod_name", "","pod")) by (pod_name) > 2
    for: 30m
    labels:
      severity: 2
    annotations:
      summary: '{{ $labels.pod_name }}, Pod CPU 单核使用率(30m) > 1, current_value: {{ $value }}, 请考虑扩容.'


  # Pod Memory Usage
  - alert: k8s-pod-memory-usage
    expr: sum (rate (container_memory_usage_bytes{image!=""}[1m])) by (pod_name) / sum(label_join(kube_pod_container_resource_requests_memory_bytes, "pod_name", "","pod")) by (pod_name) > 1
    for: 30m
    labels:
      severity: 2
    annotations:
      summary: '{{ $labels.pod_name }}, Pod Memory 单核使用率(30m) > 1, current_value: {{ $value }}, 请考虑扩容.'

  # Container CPU Usage
  - alert: k8s-Container-cpu-usage
    expr: sum (rate (container_cpu_usage_seconds_total{image!=""}[1m])) by (container_name) / sum(label_join(kube_pod_container_resource_requests_cpu_cores, "container_name", "","container")) by (container_name) > 2
    for: 30m
    labels:
      severity: 2
    annotations:
      summary: '{{ $labels.container_name }}, container CPU 单核使用率(30m) > 1, current_value: {{ $value }}, 请考虑扩容.'


  # Container Memory Usage
  - alert: k8s-container-memory-usage
    expr: sum (rate (container_memory_usage_bytes{image!=""}[1m])) by (container_name) / sum(label_join(kube_pod_container_resource_requests_memory_bytes, "container_name", "","container")) by (container_name) > 1
    for: 30m
    labels:
      severity: 2
    annotations:
      summary: '{{ $labels.container_name }}, container Memory 单核使用率(30m) > 1, current_value: {{ $value }}, 请考虑扩容.'

  # pod phase:
  - alert: k8s-pod-Pending
    expr: sum(kube_pod_status_phase{phase="Pending"}) BY (job, pod) > 5
    for: 30m
    labels:
      severity: 2
    annotations:
      summary: '{{ $labels.pod }}, pod phase Pending, current_value: {{ $value }}'

  - alert: k8s-pod-faild
    expr: sum(kube_pod_status_phase{phase="Failed"}) BY (job, pod) > 5
    for: 10m
    labels:
      severity: 1
    annotations:
      summary: '{{ $labels.pod }}, pod phase Failed, current_value: {{ $value }}'

  # containers status:
  - alert: k8s-containers-waiting
    expr: sum(kube_pod_container_status_waiting) BY (job, pod) > 10
    for: 30m
    labels:
      severity: 2
    annotations:
      summary: '{{ $labels.pod }}, container status waiting, current_value: {{ $value }}'

  - alert: k8s-containers-terminated
    expr: sum(kube_pod_container_status_terminated) BY (job, pod) > 5
    for: 10m
    labels:
      severity: 1
    annotations:
      summary: '{{ $labels.pod }}, container status terminated, current_value: {{ $value }}'

